<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c7c0299d-8371-41df-bc3e-029daca0b606</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Npgsql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlogPlatform.Shared\BlogPlatform.Shared.API\BlogPlatform.Shared.API.csproj" />
    <ProjectReference Include="..\..\BlogPlatform.Shared\BlogPlatform.Shared.Data\BlogPlatform.Shared.Data.csproj" />
    <ProjectReference Include="..\BlogPlatform.Auth.Core\BlogPlatform.Auth.Core.csproj" />
    <ProjectReference Include="..\BlogPlatform.Auth.Grpc\BlogPlatform.Auth.Grpc.csproj" />
    <ProjectReference Include="..\BlogPlatform.Auth.Infrastructure\BlogPlatform.Auth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
